import "./globals.css";

// AOS 
import AOSInit from "@/utils/aos";

export const metadata = {
  title: "LadyShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
      <AOSInit/>
        {children}
        </body>
    </html>
  );
}
