import "./globals.css";

// Components
import Navbar from "@/components/modules/navbar/Navbar";
import Footer from "@/components/modules/footer/Footer";
import AOSInit from "@/utils/aos";

export const metadata = {
  title: "LadyShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
      <Navbar/>
      <AOSInit/>
        {children}
      <Footer/>
        </body>
    </html>
  );
}
